name: JaguarDemo
description: A Demo Jaguar
version: 1.0.0
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.2.24
  jaguar_orm: ^2.2.1
  jaguar_query_postgres: ^2.2.2
  jaguar_jwt: ^2.1.5

dev_dependencies:
  build_runner:
  jaguar_orm_gen: